# Generated by Django 5.1.3 on 2025-01-18 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notesApp', '0002_remove_note_last_change_note_is_favorite_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('img_id', models.AutoField(primary_key=True, serialize=False)),
                ('note_id', models.IntegerField(blank=True, null=True)),
                ('file_name', models.TextField(blank=True, null=True)),
                ('image', models.BinaryField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='note',
            name='is_temporary',
        ),
        migrations.AddField(
            model_name='note',
            name='action_dt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='last_update',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='is_favorite',
            field=models.IntegerField(default=0),
        ),
    ]
