# Generated by Django 5.1.3 on 2025-02-17 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notesApp', '0003_image_remove_note_is_temporary_note_action_dt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='is_in_recycle',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='note',
            name='is_last',
            field=models.IntegerField(default=0),
        ),
    ]
