# Generated by Django 5.1.3 on 2025-02-18 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notesApp', '0004_alter_note_is_in_recycle_alter_note_is_last'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='pic',
            field=models.ImageField(null=True, upload_to='pics'),
        ),
    ]
