# Generated by Django 5.2a1 on 2025-02-18 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notesApp', '0005_note_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='last_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
