# Generated by Django 5.2a1 on 2025-02-19 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notesApp', '0006_alter_note_last_update'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
